[package]
name = "lelele-runtime-tests"
version = "0.0.0"
edition = "2021"
publish = false

[build-dependencies]
lelele = { path = "../lelele" }

[dependencies]
lelele-runtime = { path = "../lelele-runtime" }
