[package]
name = "lelele-runtime-tests"
version = "0.0.0"
edition = "2021"
publish = false

[build-dependencies]
anyhow = { workspace = true }
lelele = { path = "../lelele" }
lelele-syntax = { path = "../lelele-syntax" }

[dependencies]
lelele-runtime = { path = "../lelele-runtime" }
