[package]
name = "lelele-tests"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies]
lelele = { path = "../lelele" }

[dev-dependencies]
criterion = "0.5.1"

[[bench]]
name = "benches"
harness = false
