[package]
name = "lelele-runtime"
version = "0.0.0-dev"
publish = false
authors = { workspace = true }
edition = { workspace = true }
rust-version = { workspace = true }

[dependencies]
phf = { workspace = true }
thiserror = { workspace = true }
