//! code generation.

use crate::{
    dfa::{Action, NodeID, DFA},
    grammar::{Grammar, RuleID, TerminalID},
};
use std::fmt;

#[derive(Debug)]
pub struct Codegen<'g> {
    grammar: &'g Grammar,
    dfa: &'g DFA,
}

impl<'g> Codegen<'g> {
    pub fn new(grammar: &'g Grammar, dfa: &'g DFA) -> Self {
        Self { grammar, dfa }
    }

    fn fmt_preamble(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str(
            "\
// This file is automatically generated by lelele.
use ::lelele_runtime::_private as lelele;
",
        )
    }

    fn fmt_node_id_def(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str(
            "\
/// The type to identify DFA state nodes.
#[derive(Debug, Copy, Clone, PartialEq, Eq)]
#[repr(transparent)]
pub struct NodeID { __raw: usize }
impl NodeID {\n",
        )?;

        writeln!(
            f,
            "    const __START: Self = Self {{ __raw: {} }};",
            NodeID::START
        )?;

        f.write_str("}\n")?;

        Ok(())
    }

    fn fmt_token_id_def(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str(
            "\
/// The type to identify terminal or nonterminal symbols used in generated DFA.
#[derive(Copy, Clone, PartialEq, Eq)]
#[repr(transparent)]
pub struct TokenID { __raw: u64 }
impl TokenID {\n",
        )?;

        writeln!(
            f,
            "const __EOI: Self = Self {{ __raw: {} }};",
            TerminalID::EOI.raw(),
        )?;

        for terminal in self.grammar.terminals() {
            let export_name = match terminal.export_name() {
                Some(name) => name,
                None => continue,
            };
            writeln!(
                f,
                "\
/// Terminal `{export_name}`
pub const {export_name}: Self = Self {{ __raw: {id} }};",
                export_name = export_name,
                id = terminal.id().raw(),
            )?;
        }

        f.write_str(
            "}
impl ::std::fmt::Debug for TokenID {
    #[inline]
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::std::fmt::Display::fmt(self, f)
    }
}
impl ::std::fmt::Display for TokenID {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        match self.__raw {\n",
        )?;

        for symbol in self.grammar.terminals() {
            writeln!(
                f,
                "\
            {} => f.write_str(stringify!({})),",
                symbol.id().raw(),
                symbol,
            )?;
        }

        f.write_str(
            "\
            _ => f.write_str(\"<unknown>\"),
        }
    }
}",
        )?;

        Ok(())
    }

    fn fmt_symbol_id_def(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str(
            "\
/// The type to identify nonterminal symbols used in generated DFA.
#[derive(Debug, Copy, Clone, PartialEq, Eq, Hash)]
pub enum Symbol {\n",
        )?;

        for symbol in self.grammar.nonterminals() {
            let export_name = match symbol.export_name() {
                Some(name) => name,
                None => continue,
            };
            writeln!(
                f,
                "\
/// Nonterminal `{export_name}`
{export_name},",
                export_name = export_name,
            )?;
        }

        f.write_str("}\n")?;

        Ok(())
    }

    fn fmt_parser_def(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str(
            "\
/// The generated LR(1) parse table.
#[derive(Debug, Default)]
pub struct ParserDef {
    _p: (),
}
impl lelele::ParserDef for ParserDef {
    type State = NodeID;
    type Token = TokenID;
    type Symbol = Symbol;
    #[inline]
    fn initial_state(&self) -> Self::State {
        NodeID::__START
    }
    #[inline]
    fn action<TAction>(
        &self,
        current: Self::State,
        lookahead: Option<Self::Token>,
        action: TAction,
    ) -> Result<TAction::Ok, TAction::Error>
    where
        TAction: lelele::ParseAction<
            State = Self::State,
            Token = Self::Token,
            Symbol = Self::Symbol,
        >,
    {
        __action(current, lookahead.unwrap_or(TokenID::__EOI), action)
    }
    #[inline]
    fn goto(&self, current: Self::State, symbol: Self::Symbol) -> Self::State {
        __goto(current, symbol)
    }
}\n",
        )?;

        f.write_str(
            "\
#[inline]
fn __action<TAction>(
    current: NodeID,
    lookahead: TokenID,
    action: TAction,
) -> ::std::result::Result<TAction::Ok, TAction::Error>
where
    TAction: lelele::ParseAction<
        State = NodeID,
        Token = TokenID,
        Symbol = Symbol,
    >,
{
    match current.__raw {\n",
        )?;

        for (id, node) in self.dfa.nodes() {
            writeln!(f, "{} => match lookahead.__raw {{", id)?;
            for (lookahead, action) in node.actions() {
                let action_g = match action {
                    Action::Shift(n) => {
                        format!("action.shift(NodeID {{ __raw: {} }}),", n)
                    }
                    Action::Reduce(rule) if *rule == RuleID::ACCEPT => {
                        format!("action.accept(),")
                    }
                    Action::Reduce(rule) => {
                        let rule = self.grammar.rule(rule);
                        let left = self
                            .grammar
                            .nonterminal(&rule.left())
                            .export_name()
                            .unwrap();
                        format!(
                            "action.reduce(Symbol::{left}, {n}),",
                            left = left,
                            n = rule.right().len(),
                        )
                    }
                    _ => continue,
                };
                writeln!(f, "  {} => {}", lookahead.raw(), action_g)?;
            }

            let available_lookaheads: String =
                node.actions()
                    .enumerate()
                    .fold(String::new(), |mut buf, (i, (t, _))| {
                        if i > 0 {
                            buf += ", ";
                        }
                        buf += &format!("TokenID {{ __raw: {} }}", t.raw());
                        buf
                    });
            writeln!(
                f,
                "\
#[allow(unreachable_patterns)] _ => {{
    action.fail([{}])
}},
}}",
                available_lookaheads
            )?;
        }
        f.write_str(
            "\
#[allow(unreachable_patterns)]
_ => unreachable!(),
}
}\n",
        )?;

        f.write_str(
            "\
#[inline]
fn __goto(current: NodeID, symbol: Symbol) -> NodeID {
    match current.__raw {\n",
        )?;

        for (id, node) in self.dfa.nodes() {
            if node.gotos().count() == 0 {
                continue;
            }
            writeln!(f, "{} => match symbol {{", id)?;
            for (symbol, target) in node.gotos() {
                let symbol = self.grammar.nonterminal(&symbol).export_name().unwrap();
                writeln!(f, "  Symbol::{} => NodeID {{ __raw: {} }},", symbol, target)?;
            }
            writeln!(f, "  #[allow(unreachable_patterns)] _ => unreachable!(),")?;
            writeln!(f, "}},")?;
        }

        f.write_str("#[allow(unreachable_patterns)] _ => unreachable!(),\n}\n}\n")?;

        Ok(())
    }
}

impl<'g> fmt::Display for Codegen<'g> {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        self.fmt_preamble(f)?;
        self.fmt_node_id_def(f)?;
        self.fmt_token_id_def(f)?;
        self.fmt_symbol_id_def(f)?;
        self.fmt_parser_def(f)?;
        Ok(())
    }
}
