[package]
name = "lelele"
version = "0.0.0-dev"
authors = { workspace = true }
edition = { workspace = true }
rust-version = { workspace = true }
publish = false

[dependencies]
indexmap = { workspace = true }
rustc-hash = { workspace = true }
unicode-ident = { workspace = true }
